### ISSUE TITLE
Selecting a TableView Cell Should Not Highlight Cell

### ISSUE THREAD

**Issue by hlpostman** [hlpostman/Flicks#3]
You can't set `tableView.allowsSelection` to `false` because then you cannot interact with the cell to get push to the details view controller.

**Comment by kmolo** [comment]
@hlpostman you should post these "Issues" as questions in the Discussions.codepath.com forum, as that's where CodePath is expecting to see them.  They don't really have as much visibility here (only weekly when the `@codepathreviewer` account looks at weekly assignment will they see them).

**Comment by hlpostman** [comment]
@kmolo Okay cool, yeah. I wasn't actually expecting help on them, I just posted them for my own tracking purposes. I'll keep the discussions forum in mind! Thanks for the FYI.

**Comment by hlpostman** [comment]
Fixed in commit 6978679b443e5199bdc5b2a032369d721edc26a2
